- 
    name: Formation Ansible Playbook
    hosts: all # tous les groupes (définis dans le fichier hosts) sont ciblés 
    become: yes # become root
    vars:
        users: ['portos', 'athos', 'aramis']

    tasks:
        - name: Install Apache + Php
          apt: name={{ item }} state=latest
          loop: ['apache2', 'php', 'libapache2-mod-php', 'php-mysql']

        - name: Start Apache
          service: name=apache2 state=reloaded

        - name: Create Group musketeers
          group: name=musketeers state=present

        # N.B: module random pour génération  de chaînes aléatoires
        - name: Create user {{ item }}
          user: name={{ item }} state=present groups=musketeers
          loop: "{{ users }}"

        - name: Create user folder in Apache document root
          file: path=/var/www/html/{{ item }} state=directory
          loop: "{{ users }}"

        - name: Copy php files
          copy: src=files/index.php dest=/var/www/html/{{ item }}/index.php owner={{ item }}
          loop: "{{ users }}"
          
        # Il est possible d'exécuter des commandes système par
        # le module command ou par le module shell
        # - name: Touch a file
        #   command: touch /tmp/cgi_temp_file

    # roles:
    #     - container

- 
  name: Create MariaDb container on Local VMs
  hosts: local_vm 
  become: yes
  roles:
    - container
    
- 
  name: Create MariaDb container on AWS EC2 instances
  hosts: aws 
  become: yes
  roles:
    - docker
    - container-aws

