version: '3'

services:
    mariadb:
        image: mariadb
        ports:
            - "0.0.0.0:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=azerty
            - MYSQL_DATABASE=test